name: CookMate
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  sqflite: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/recipes.json
  fonts:
    - family: Hoefler
      fonts:
        - asset: assets/fonts/hoefler/HoeflerText-Regular.ttf
          weight: 300
        - asset: assets/fonts/hoefler/HoeflerText-Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/hoefler/HoeflerText-Black.ttf
          weight: 500
        - asset: assets/fonts/hoefler/HoeflerText-BlackItalic.ttf
          weight: 500
          style: italic
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 200
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 400
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 500
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
          weight: 500
          style: italic
