import 'dart:collection';
import 'dart:convert';

import 'package:CookMate/entities/shoppingIngredient.dart';
import 'package:flutter/services.dart';
import 'package:fuzzy/fuzzy.dart';
import 'package:hive/hive.dart';
import 'package:path_provider/path_provider.dart' as path_provider;

import '../entities/recipe.dart';
import '../entities/shoppingIngredient.dart';
import '../enums/category.dart';

abstract class DB {
  static Box categories;
  static Box recipes;
  static Box recipeTitles;
  static Box ingredients;
  static Box favorites;
  static Box featured;
  static Box shoppingList;
  static Box shoppingListItem;

  static Future<void> init() async {
    // Setup Hive:
    final appDir = await path_provider.getApplicationDocumentsDirectory();
    Hive.init(appDir.path);

    // Open Hive Boxes
    categories = await Hive.openBox('categories');
    recipes = await Hive.openBox('recipes');
    recipeTitles = await Hive.openBox('recipeTitles');
    ingredients = await Hive.openBox('ingredients');
    favorites = await Hive.openBox('favorites');
    featured = await Hive.openBox('featured');
    shoppingList = await Hive.openBox('shoppingList');
    shoppingListItem = await Hive.openBox('shoppingList');

    // Insert Hive Data
    await insertHiveData();
  }

  static Future<void> insertHiveData() async {
    // Recipes
    String jsonRecipes = await rootBundle.loadString('assets/recipes.json');
    recipes.putAll(json.decode(jsonRecipes));
    // Ingredients
    String jsonIng = await rootBundle.loadString('assets/ingredients.json');
    ingredients.putAll(json.decode(jsonIng));
    // Recipe Titles
    String jsonTitles = await rootBundle.loadString('assets/titles.json');
    recipeTitles.putAll(json.decode(jsonTitles));
    // Categories With Recipes
    String jsonCats = await rootBundle.loadString('assets/categories.json');
    categories.putAll(json.decode(jsonCats));
    return;
  }

  /*
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    FAVORITES
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

  static List<Recipe> getFavoriteRecipes() {
    List<Recipe> allFaves = List<Recipe>();
    favorites.toMap().forEach((key, value) async {
      print("$key : $value");
      Recipe favorite = await getRecipeWithID(key);
      allFaves.add(favorite);
    });
    return allFaves;
  }

  static void addToFavorites(int id) async {
    // var favorites = await Hive.openBox('favorites');
    print("Adding $id to favorites...");
    favorites.put(id, 1);
  }

  static void removeFromFavorites(int id) async {
    // var favorites = await Hive.openBox('favorites');
    print("Removing $id from favorites...");
    favorites.delete(id);
  }

  static Future<bool> isRecipeAFavorite(int recipeID) async {
    // var favorites = await Hive.openBox('favorites');
    var found = favorites.containsKey(recipeID);
    // print("Looking for recipe $recipeID");
    // print("Was found: $found");
    return found;
  }

  static Future<Recipe> getRecipeWithID(int recipeID) async {
    // var recipes = await Hive.openBox('recipes');
    var found = recipes.get("$recipeID");
    found['id'] = recipeID;
    return Recipe.fromHive(found);
  }
/*
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    FEATURED
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

  static Future<void> getFeaturedRecipes() {
    // For now just grab random recipes.
  }

/*
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CATEGORY
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */
  static Future<List<Recipe>> getRecipesByCategory(Category category) async {
    // Pull all recipes ids with given category.
    List<dynamic> recipesWithGivenCategory = categories.get(catToString(category));
    // Grab a recipe object from the given list of ids.
    List<Recipe> results = List<Recipe>();
    recipesWithGivenCategory.forEach((recipeID) async {
      Recipe rec = await getRecipeWithID(int.parse(recipeID));
      results.add(rec);
    });
    return results;
  }

/*
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    INGREDIENT
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

// Find ingredient using fuzzy search given a substring
// Use Fuzzy search
  static Future<List<String>> findIngredients(String ingredient) async {
    final ingList = [
      '21 seasoning salute',
      '3 grain tempeh',
      'acai',
      'acorn squash',
      'agave',
      'agave sweetener',
      'agave syrup',
      'aioli',
      'alfredo sauce',
      'all purpose flour',
      'all-purpose flour',
      'almond beverage',
      'almond beverage - choose your favorite variety!',
      'almond butter',
      'almond flour',
      'almond meal',
      'almond milk',
      'almond spread',
      'almondina cookies',
      'almonds',
      'aloha rolls',
      'also need 10 wooden craft sticks and 10 small paper cups to use as molds',
      'also need 12 wooden craft sticks, 12 small square pieces of foil and 12 small paper cups to use as molds',
      'anchovy fillets in olive oil',
      'apple',
      'apple cider',
      'apple cider jam',
      'apple cider vinegar',
      'apple juice',
      'apple sauce',
      'apples',
      'apricot',
      'apricots',
      'arrabiata sauce',
      'artichoke',
      'artichokes',
      'arugula',
      'asparagus',
      'avocado',
      'avocado oil',
      'avocado tzatziki dip',
      "avocado's number guacamole",
      'avocados',
      'baby potatoes',
      'baby spinach',
      'bacon',
      'bagel',
      'bagels',
      'baguette',
      'baked beans',
      'baking powder',
      'baking sheet',
      'baking soda',
      'balsamic glaze',
      'balsamic vinaigrette',
      'balsamic vinegar',
      'balsamic vinegar of modena',
      'banana',
      'banana bread mix',
      'bananas',
      'bangers & gravy',
      'barbeque sauce',
      'basil',
      'bavarian',
      'bbq sauce',
      'bean dip',
      'beans',
      'beef',
      'beef hash',
      'beets',
      'bell pepper',
      'bell peppers',
      'berry medley',
      'big soft pretzels',
      'biscuits',
      'black beans',
      'black olives',
      'black pepper',
      'blackberry',
      'blarney scone',
      'blondie bar baking mix',
      'blood orange',
      'blood oranges',
      'bloody mary mixer',
      'blue cheese',
      'blueberries',
      'blueberry',
      'boatswain chocolate stout',
      'bok choy',
      'bourbon',
      'bran flakes',
      'bratwurst',
      'bread',
      'breadcrumbs',
      'brewed ginger beer',
      'brie',
      'brioche',
      'british muffins',
      'broccoli',
      'broccoli slaw',
      'broth',
      'brown rice',
      'brown rice & quinoa fusilli pasta',
      'brown sugar',
      'brownie mix',
      'brownie truffle baking mix',
      'brussel sprouts',
      'brussels sprouts',
      'bundt pan',
      'buns',
      'burger',
      'burrata',
      'butter',
      'butter lettuce',
      'buttermilk',
      'buttermilk biscuits',
      'buttermilk pancake mix',
      'butternut squash',
      'cabbage',
      'camembert',
      'cane sugar',
      'canola oil',
      'canola oil spray',
      'canola spray',
      'cantaloupe',
      'capers',
      'caramel',
      'caramel sauce',
      'caramel squares',
      'carne asada',
      'carnitas',
      'carrot',
      'carrots',
      'cashew',
      'cashews',
      'cauliflower',
      'cauliflower crust',
      'cayenne',
      'cayenne pepper',
      'celery',
      'cereal',
      'chai tea',
      'channa masala',
      'cheddar',
      'cheddar cheese',
      'cheddar rockets',
      'cheese',
      'cherries',
      'cherry juice',
      'chestnuts',
      'chevre',
      'chevre goat cheese log',
      'chevre log with honey',
      'chia seeds',
      'chicken',
      'chicken & bell pepper sausage',
      'chicken breasts',
      'chicken broth',
      'chicken sausage',
      'chicken stock',
      'chicken strips',
      'chile lime seasoning',
      'chile lime seasoning blend',
      'chile pepper',
      'chiles',
      'chili',
      'chili blend',
      'chilli',
      'chimichurri rice',
      'chips',
      'chives',
      'chocolate',
      'chocolate chip cookie dough',
      'chocolate chip cookies',
      'chocolate chips',
      'chocolate covered strawberries',
      'chocolate drops',
      'chocolate fudge sauce',
      'chocolate lava cakes',
      'chocolate peppermint loaf & baking mix',
      'chocolate pudding',
      'chocolate syrup',
      'chopped',
      'chorizo',
      'chunky artichoke & jalapeno dip',
      'chunky blue cheese dressing & dip',
      'chutney',
      'ciabatta',
      'cider',
      'cilantro',
      'cilantro dressing',
      'ciliegene whole milk fresh mozzarella',
      'cinnamon',
      'cinnamon rolls',
      'cinnamon squares',
      'cinnamon sticks',
      'clementines',
      'cocoa almond spread',
      'cocoa powder',
      'coconut',
      'coconut aminos',
      'coconut chips',
      'coconut cream',
      'coconut milk',
      'coconut oil',
      'coconut oil spray',
      'coconut water',
      'cod',
      'coffee',
      'coffee concentrate',
      'coffee ice cream',
      'cole slaw',
      'cookie butter',
      'cookie butter cookies',
      'cookie butter cream cheese',
      'cookie cutter',
      'cookie dough',
      'cookies',
      'cooking oil spray',
      'corn',
      'corn chip dippers',
      'corn tortillas',
      'cornbread',
      'cornbread baking mix',
      'cornbread mix',
      'cornbread stuffing mix',
      'corned beef',
      'cornichons',
      'cotija cheese',
      'cottage cheese',
      'crackers',
      'cranberries',
      'cranberry',
      'cranberry chevre',
      'cream',
      'cream cheese',
      'creme fraiche',
      'crimini mushrooms',
      'crisps',
      'croissants',
      'cruciferous crunch',
      'cruciferous crunch collection',
      'crème fraiche',
      'cuban style citrus garlic bowl',
      'cucumber',
      'cucumbers',
      'cultured salted butter',
      'cumin',
      'cupcake liners',
      'curry',
      'curry sauce',
      'dark chocolate',
      'date',
      'dates',
      'diced',
      'dijon mustard',
      'dill',
      'dip',
      'dipping sauce',
      'dish',
      'dressing',
      'drumsticks',
      'edamame',
      'egg',
      'egg frittata',
      'egg nog',
      'egg salad',
      'egg yolks',
      'eggs',
      'enchilada sauce',
      'enchilada sauce divided',
      'endives',
      'espresso beans',
      'everyday seasoning',
      'everything bagels',
      'everything but the bagel sesame seasoning blend',
      'everything but the elote seasoning blend',
      'falafel',
      'farfalle',
      'fennel',
      'feta',
      'feta cheese',
      'fig butter',
      'figs',
      'fish',
      'flaxseed',
      'flaxseed meal',
      'flour',
      'french brioche',
      'fresh mozzarella balls',
      'fresh ravioli',
      'frozen mashed sweet potatoes',
      'frozen meatballs',
      'frozen melange a trois',
      'frozen organic mixed berry blend',
      'fudge ice cream',
      'fudge sauce',
      'garlic',
      'garlic aioli',
      'garlic powder',
      'ghee',
      'gin',
      'ginger',
      'ginger beer',
      'ginger snaps',
      'glaze',
      'gluten free cocoa crunch cereal',
      'gnocchi',
      'goat cheese',
      'gone bananas',
      'gouda',
      'graham crackers',
      'granola',
      'granola cereal',
      'grape tomato',
      'grape tomatoes',
      'grapes',
      'grapeseed oil',
      'gravy',
      'greek yogurt',
      'green bell peppers',
      'green chiles',
      'green dragon sauce',
      'green jackfruit in brine',
      'green onion',
      'green onions',
      'green tea',
      'grill',
      'ground beef',
      'ground black pepper',
      'ground buffalo burgers',
      'ground cinnamon',
      'ground pepper',
      'ground turkey',
      'gruyere cheese',
      'guacamole',
      'gyoza',
      'half &half',
      'ham',
      'hamburger buns',
      'haricots verts',
      'harissa',
      'harvest blend herbal tea',
      'hash browns',
      'heavy cream',
      'heavy whipping cream',
      'hemp seed',
      'honey',
      'honey yogurt',
      'hot dog buns',
      'hot sauce',
      'hot water',
      'hummus',
      'ice',
      'ice cream',
      'instant coffee',
      'irish bangers',
      'irish stout',
      'island salsa',
      'island soyaki',
      'israeli couscous',
      'jackfruit',
      'jalapeno',
      'jalapenos',
      'jalapeño',
      'jalepeños',
      'jam',
      'jar',
      "joe's diner macaroni & cheese",
      "joe-joe's",
      'josephsbrau bohemian lager',
      'josephsbrau pilsner',
      'josephsbrau plznr, chilled',
      'jumbo raisin medley',
      'just almond meal',
      'kale',
      'kernel corn',
      'ketchup',
      'lager',
      'lasagna noodles',
      'le rustique camembert',
      'leeks',
      'lemon',
      'lemon curd',
      'lemon ginger echinacea juice blend',
      'lemon juice',
      'lemon pepper',
      'lemon pepper seasoning',
      'lemon thins',
      'lemonade',
      'lemons',
      'lemons &cilantro',
      'lentil',
      'lentils',
      'lettuce',
      'lime',
      'lime juice',
      'limeade',
      'limes',
      'linguine',
      "mac n' cheese",
      'macaroons',
      'malabari paratha',
      'mango',
      'mango chunks',
      'mango pineapple salsa',
      'mango sorbet',
      'mango yogurt',
      'maple pecan shortbread bar mix',
      'maple syrup',
      'margarita mixer',
      'marinara',
      'marinara sauce',
      'marmalade',
      'marshmallows',
      'mascarpone',
      'mascarpone cheese',
      'mashed potatoes',
      'matcha green tea',
      'mayo',
      'mayonnaise',
      'meatballs',
      'meatless meatballs',
      'medley',
      'melon',
      'mexican cheese',
      'microgreens',
      'milk',
      'milk chocolate',
      'mini dark chocolate mint stars',
      'mint',
      'mirepoix',
      'miso ginger broth',
      'miso vegetable & brown rice saute kit',
      'mochi cake mix',
      'molasses',
      'morsels',
      'mozzarella',
      'mozzarella cheese',
      'muffin mix',
      'muffin pan',
      'muffin tin',
      'multigrain bread',
      'mushroom medley',
      'mushrooms',
      'mustard',
      'mélange a trois peppers',
      "neapolitan joe-joe's",
      'nectarines',
      'non-dairy oat beverage',
      'noodle',
      'noodles',
      'nori komi furikake',
      'nuggets',
      'nutmeg',
      'nuts',
      'oats',
      'oil',
      'oil spray',
      'oilve oil',
      'olive oil',
      'olive oil cooking spray',
      'olive oil spray',
      'olive tapenade',
      'olives',
      'onion',
      'onion dip',
      'onion salt',
      'onions',
      'orange',
      'orange juice',
      'oranges',
      'oregano',
      'organic chickpea & red lentil risoni',
      'organic coconut aminos',
      'organic cold pressed green juice beverage',
      'organic elote corn chip dippers',
      'organic garlic',
      'organic kosher hot & spicy dill pickle chips',
      'organic power to the greens',
      'organic shredded green & red cabbage with orange carrots',
      'organic sriracha and roasted garlic bbq sauce',
      'organic tomato & roasted red pepper soup',
      'organic virgin coconut oil packet',
      'oyster crackers',
      'palak paneer',
      'pan',
      'pan dripping',
      'pancackes',
      'pancake mix',
      'panettone',
      'papaya',
      'paper cups',
      'paprika',
      'parchment paper',
      'parmesan',
      'parmesan cheese',
      'parmigiano cheese',
      'parsley',
      'pasta',
      'pasta sauce',
      'peach',
      'peach slices',
      'peaches',
      'peanut',
      'peanut and crispy noodle salad kit',
      'peanut butter',
      'peanut butter cups',
      'peanut vinaigrette',
      'peanuts',
      'pear',
      'peas',
      'pecan',
      'pecans',
      'pecorino',
      'pepper',
      'pepper jelly',
      'pepper spread',
      'pepperoni',
      'peppers',
      'persimmons',
      'peruvian style chimichurri rice with vegetables',
      'pesto',
      'pesto gouda cheese',
      'pickle',
      'pickles',
      'pico de gallo',
      'pie crust',
      'pie crusts',
      'pie dish',
      'pie pumpkin',
      'pine nuts',
      'pineapple',
      'pineapple juice',
      'pineapple spears',
      'pistachio',
      'pita',
      'pita chips',
      'pizza crust',
      'pizza dough',
      'pizza sauce',
      'plain pizza dough',
      'plain sparkling mineral water',
      'plastic wrap',
      'plus 1 tablespoon cold water',
      'polenta',
      'pollo asado autentico',
      'pomegranate',
      'pomegranate seeds',
      'popcorn in a pickle',
      'popping corn',
      'pork',
      'pork belly',
      'portobello mushrooms',
      'potato',
      'potato chips',
      'potato pancakes',
      'potato tots',
      'potatoes',
      'powder',
      'powdered sugar',
      'pretzel',
      'pretzel slims',
      'prosciutto',
      'protein powder',
      'pulled pork',
      'pumpkin',
      'pumpkin bread mix',
      'pumpkin butter',
      'pumpkin cheesecake',
      'pumpkin cookies',
      'pumpkin ice cream',
      'pumpkin pie',
      'pumpkin pie pumpkin',
      'pumpkin pie spice',
      'pumpkin pie spiced ginger brew',
      'pumpkin seeds',
      'quick cook farro',
      'quick cook steel cut oats',
      'quinoa',
      'radish',
      'raisin',
      'raisins',
      'ramekins',
      'ranch dressing',
      'raspberries',
      'raspberry',
      'raspberry preserves',
      'ravioli',
      'raw sauerkraut',
      'red bell pepper',
      'red chili flakes',
      'red onion',
      'red onions',
      'red pepper flakes',
      'red peppers',
      'red wine vinegar',
      'relish',
      'rice',
      'rice crackers',
      'rice crumbs',
      'rice vinegar',
      'ricotta',
      'ricotta cheese',
      'roasted potatoes with peppers & onions',
      'rocotta',
      'rolled oats',
      'rolls',
      'romaine hearts',
      'rosemary',
      'rum',
      'sage',
      'salad',
      'salad dressing',
      'salame',
      'salmon',
      'salsa',
      'salsa verde',
      'salt',
      'salt & pepper',
      'salt and pepper',
      'sandwich cookies',
      'sardines',
      'sauce',
      'sausage',
      'sausages',
      'scallops',
      'scone',
      'sea salt',
      'sea salt & black pepper',
      'sea salt & ground black pepper',
      'sea salt & pepper',
      'sea salt, sliced almonds, sweet & spicy pecans, pistachios, sunflower seeds.',
      'seaweed',
      'secco peach bellini',
      'sesame oil',
      'sesame oil & soy sauce',
      'sesame seed oil',
      'sesame sticks',
      'shakshuka starter',
      'shallot',
      'shallots',
      'shishito peppers',
      'shortbread cookies',
      'shortcake biscuits',
      'shredded cabbage',
      'shredded fancy mexican style cheese blend divided',
      'shredded mozzarella cheese',
      'shrimp',
      'simpler times lager',
      'simply almond beverage',
      'skewers',
      'sliced halloumi cheese',
      'smoked paprika',
      'soup',
      'sour cream',
      'south african seasoning blend',
      'south african smoke seasoning',
      'soy chorizo',
      'soy sauce',
      'soyaki',
      'soyaki sauce',
      'soycutash',
      'spaghetti',
      'spaghetti squash',
      'sparkling cranberry juice',
      'sparkling lime water',
      'sparkling wine',
      'speculoos cookies',
      'spiced apple cider',
      'spiced cider',
      'spices',
      'spices of the world',
      'spicy chai tea latte mix',
      'spinach',
      'spinanch',
      'spring mix',
      'sprouts',
      'squares of foil',
      'squash',
      'sriracha',
      'sriracha sauce',
      'steak',
      'steamer basket',
      'steel bowl',
      'sticks',
      'stir fry veggies',
      'storage containers',
      'strawberries',
      'strawberry',
      'strawberry preserves',
      'sugar',
      'sundried tomatoes',
      'sunflower oil',
      'sunflower seed spread',
      'sweet',
      'sweet chili sauce',
      'sweet italian sausage link',
      'sweet onion',
      'sweet potatoes',
      'swiss cheese',
      'syrup',
      'taco sauce',
      'taco seasoning',
      'taco shells',
      'tahini',
      'taquitos',
      'tea',
      'tempeh',
      'tequila',
      'thyme',
      'tilapia',
      'tin foil',
      'toffee pretzels',
      'tofu',
      'tomato',
      'tomato juice',
      'tomato sauce',
      'tomatoes',
      'toothpicks',
      'tortilla',
      'tortilla chips',
      'tortillas',
      'toscana cheese',
      'trader potato tots',
      'traditional tunisian harissa',
      'trek mix',
      'truffle brownie mix',
      'tuna',
      'turkey',
      'turkey bacon',
      'turkey bolognese',
      'turkey burgers',
      'turkey chili',
      'turkey neck',
      'turkey stock',
      'turmeric ginger coconut beverage',
      'turmeric powder',
      'twine',
      'umami',
      'unsalted butter',
      'unsweetened original almond beverage',
      'unsweetened vanilla almond beverage',
      'vanilla',
      'vanilla baking mix',
      'vanilla bean cake',
      'vanilla cake & baking mix',
      'vanilla extract',
      'vanilla ice cream',
      "vanilla joe-joe's",
      'vanilla mix',
      'vegan chicken-less seasoning salt',
      'vegetable',
      'vegetable broth',
      'vegetables',
      'veggie burgers',
      'vinaigrette',
      'vinegar',
      'vodka',
      'wafer cookies',
      'waffle',
      'waffle cookies',
      'waffle iron',
      'waffles',
      'walnut',
      'walnuts',
      'water',
      'water crackers',
      'watermelon',
      'wheat',
      'whipped cream',
      'whipped light cream',
      'whipping cream',
      'white beans',
      'white wine',
      'whole milk',
      'winter wassail',
      'yeast',
      'yellow onion',
      'yogurt',
      'zhoug sauce',
      'zucchini'
    ];
    final fuse = Fuzzy(
      ingList,
      options: FuzzyOptions(
        findAllMatches: true,
        tokenize: true,
        threshold: 0.3,
      ),
    );

    final result = fuse.search(ingredient);
    List<String> searchResults = List<String>();
    result.forEach((element) {
      searchResults.add(element.item);
    });
    return searchResults;
  }

// Returns all recipes that have given ingredients
  static Future<List<String>> getRecipesWithIngredients(List<String> ing) async {
    List<String> results = List<String>();
    for (var ingredient in ing) {
      if (ingredients.containsKey(ingredient)) {
        List<dynamic> recipeIDs = ingredients.get(ingredient);
        recipeIDs.forEach((id) {
          results.add(id);
        });
      }
    }
    return results;
  }

/*
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    RECIPE
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */
  // Find recipe by substring using fuzzy search
  static Future<List<int>> findRecipe(String recipe) async {
    final titles = [
      '1 Minute Lentil Salad',
      '21 Seasoning Salute Vinaigrette',
      'Acorn Squash Polenta Stacks',
      'Acorn Squash Tacos',
      'Almond Satay Sauce',
      'Almondina Cookies',
      'Antipasti Bowl',
      'Apple-Caramel Hand Pies',
      'Apricot Jubilees',
      "Asian Inspired Philly Smoked Salmon Hors d'oeuvres",
      'Avocado Crema',
      'Acai Smoothie Bowl',
      'BABP (Bacon, Apple & Brie Panini)',
      'BBQ Baked Beans',
      'BLT Salad & Croutons',
      'Bacon Apple Sweet Potato Hash',
      'Bacon, Apple, and Butternut Squash Salad',
      'Baked Apples',
      'Baked Banana Pudding',
      'Baked Parmesan Chicken Tenders',
      'Baked Pear with Yogurt and Granola',
      'Baked Taco Snack Mix',
      'Balsamic Caramelized Onions',
      'Balsamic Lentil Saute',
      'Bared Bacon Cheddar Cornbread Cake',
      'Basic Breakfast Sandwich',
      'Beef-less Burritos',
      'Beef-less Tacos',
      'Berry Best Bran Muffins',
      'Berry Crazy Sundae',
      'Berry Yogurt Pops',
      'Biscuits & Gravy Casserole',
      'Biscuits & Maple Turkey Gravy',
      'Biscuits & Spicy Soy Chorizo Gravy',
      'Blarney Toast',
      'Blood Orange & Butter Lettuce Salad with Avocado, Fennel & Feta',
      'Blueberry Corn Cake',
      'Blueberry Protein Pancakes',
      'Blueberry-Lemon Hand Pies',
      'Boatswain Chocolate Stout Float',
      'Braised Chicken',
      'Breakfast Casserole',
      'Breakfast Tacos',
      'Brie-lieve it or not',
      'Brunch Fried Rice',
      'Brunchfast Burritos',
      'Buffalo Fig Burger',
      'Butter Toffee Pretzel Bark',
      'Buttermilk Drumsticks',
      'Butternut Squash Hummus',
      'Caprese BLT',
      'Caprese Risoni',
      'Caramel Dipped Persimmons',
      'Caramel Pumpkin Cheesecake',
      'Carne Asada Salad',
      'Carnitas Bowl',
      'Carnitas Tacos',
      'Carolina Gold Slaw',
      'Cashew Chicken Lettuce Wraps',
      'Channa Masala Pasties',
      'Channa Masala Tomato Soup',
      "Charlotte's Chocolate Bread Pudding",
      'Cheeseburger Pizza',
      'Cheesy Baguette',
      'Cheesy Chili-Garlic Dipping Oil',
      'Cheesy Hash Brown Casserole',
      'Cheesy Hot Pepper Pasta',
      'Cheesy Jalapeno Beer Bread',
      'Cheesy Red Pepper Pizza',
      'Cheesy Tot Breakfast Bake',
      'Cheesy Truffle Snack Mix',
      'Cherry Citrus Punch',
      'Cherry Cocoa-Almond Hand Pies',
      'Cherry Galette',
      'Cherry Pistachio Galette',
      'Chewy Chocolate Mochi Cake',
      "Chicken Breast Stuffed with Bacon 'n Feta",
      'Chicken Sausage & Lentil Soup',
      'Chicken-less Pineapple Salad',
      'Chili Cornbread Casserole',
      'Chimichurri Soup',
      'Chimichurri Stir-Fry',
      'Chimichurri Toasts',
      'Chocolate Cream Pie',
      'Chocolate Dipped Pumpkin Pie Bites',
      'Chocolate Dipped Raspberry Stars',
      'Chocolate Maple Pecan Shortbread Bars',
      'Chocolate Mint Star Brownies',
      'Chocolate Pistachio Lava Cake',
      'Chocolate Truffles',
      'Chunky Salsa with Cream Cheese',
      'Chevre With Honey Brioche Toasts',
      'Cilantro Crema',
      'Cinnamon Bear Toast',
      'Citrus Garlic Chicken Tacos',
      'Citrusy Baked Oatmeal',
      'Classic Cobb Salad',
      'Classic Cranberry Chestnut Stuffing',
      'Classic Meatball Subs',
      'Classic Turkey Pot Pie',
      'Cobb Salad Stuffed Eggs',
      'Cocoa Almond & Banana Stuffed French Toast',
      'Cocoa Almond Crepe Wafer Cookies',
      'Cocoa Crunch Milkshake',
      'Cocoa Peanut Butter Bacon Bagel',
      'Coconut Caramel Sauce',
      'Coconut Cold Brew Ice Pops',
      'Coconut Cream Pie',
      'Coconut Water Smoothie',
      'Coconut White Hot Chocolate',
      'Con Fusion Steak Tacos',
      'Cookie Butter & Bacon Stuffed French Toast',
      'Cookie Butter Sandwich',
      'Cool & Spicy Noodle Salad',
      'Corn Chip Dipper Chili Pie',
      'Corn Flake-Crusted Brioche French Toast',
      'Corn Salsa Salad',
      'Cornfetti Rice with Shrimp',
      'Corny Chicken Poblano Ravioli',
      'Corny Squash Soup',
      'Cowboy Quinoa Bake',
      'Cranberry Baked Camembert Cheese',
      'Cranberry Endives',
      'Cranberry Orange Cornbread',
      'Crazy for Rustic Kale Pies',
      'Creamy Chicken Gnocchi Soup',
      'Creamy Pesto Chicken & Broccoli Bow Tie Pasta',
      'Creamy Smoked Salmon Linguine & Capers',
      'Crispy Tofu Sesame Salad',
      'Crunchy Chicken Sandwich',
      'Crunchy Pita Salad',
      'Cumin-y Riced Cauliflower',
      'Curried Chicken Papaya',
      'Curry Chicken Pot Pie',
      "Dairy Free Mac 'n Cheese",
      'Daylight Savings Sundae',
      'Decadence on Display Cake',
      'Delicata Squash Pasta Salad',
      'Double Chocolate Triple Ginger Tart',
      'Double Elote Crispy Chicken Tenders',
      'Double-Dressed Arugula & Burrata Salad',
      'Easy As Crispy Corned Beef Hash',
      'Easy As Pumpkin Pie',
      'Easy Bolognese-y',
      'Easy Mocha Mud Pie',
      'Edamame Energy Bowl',
      'Egg & Pesto Prosciutto Nests',
      'Egg JoeMuffin',
      'Egg Nog Breakfast Bowl',
      'Egg Nog Cake with Rum Buttercream Frosting',
      'Egg Nog Milkshake',
      'Egg Salad Bagel',
      'Elote Potato Salad',
      'Elote-Jalapeno Cornbread Pancakes',
      'Enchilada Pie',
      'Everything Cream Cheese Crispbreads',
      'Everything Ham & Cheese Roll-Ups',
      'Everything but the Bagel Dip',
      'Falafel Scones with Harissa Yogurt',
      'Falafel Surprise',
      'Falafel Waffles',
      'Falafel Wraps with Amba Mango Sauce',
      'Fall Sparkler',
      'Fall Turkey Chili With Pumpkin',
      'Family Style Wedge Salad',
      'Fancy Figgy Glazed Chicken',
      'Fancy Lemon Farfalle',
      'FauxRench Onion Burger Sliders',
      'Fiesta Bowl with Mexican Rice',
      'Fifty Fifty Toast',
      'Fig Butter Cream Cheese Bagel',
      'Filet & Rib Eye Burger',
      'Five-ish Layer Dip',
      'For The Love Of Pumpkin (Cheesecake)',
      "Frank's Blueberry Muffins",
      'Fridge-Foraged Fried Rice',
      'Fried Ravioli with Creamy Marinara',
      'Fruit & Cashew Butter Toast',
      'Fudge Chip Ice Cream Sandwiches',
      'Full Irish-ish Breakfast',
      'Fusilli Garden Pasta',
      'G.O.A.T. (Greatest Of All Toast)',
      'Garlic Potato Pizza',
      'Ginger Honey Pickled Peaches',
      'Ginger Molasses Ice Cream Sandwiches',
      'Gingerosa',
      'Gnocchi with Bacon & Brussels Sprouts',
      'Golden Milk Coconut Chia Pudding',
      'Gone Bananas Sundae',
      'Good As Gold Mini Meatballs',
      'Gouda Vibes Summer Cheese Plate',
      'Grandmas Chinese Chicken Salad',
      "Grandmommy's Gravy",
      'Greek Green Salad',
      'Greek Style Potato Salad',
      'Green Curry Chickpeas',
      'Green Dragon Fish Tacos',
      'Green Goddess Grilled Corn',
      'Green Goddess Pasta Salad',
      'Green Juice Smoothie',
      'Griddled Pepper Jelly & Cream Cheese',
      'Grilled Asparagus Salad',
      'Grilled Blue Cheese, Apricots & Spicy Pecans',
      'Grilled Camembert, Apple & Prosciutto',
      'Grilled Caprese on Cauliflower Crust',
      'Grilled Carrot Miso Salmon',
      'Grilled Nectarine Shortcake & Sriracha BBQ Glaze',
      'Grilled Peach Salad',
      'Grilled Romaine Hearts',
      'Grilled Sharp Cheddar, Applewood Bacon, & Shaved Sprouts',
      'Grilled Tempeh with Mexican Style Corn & Quinoa Salad',
      'Halloumi & Watermelon Balsamic Bites',
      'Harissa Potato Salad',
      'Harvest Grain Sweet Potatoes',
      'Harvest Pasta Sauce',
      'Here We Come A-Wassailing',
      'Honey Roasted Feta',
      'Hot & Smoky Rigatoni Bake',
      'Hot & Spicy Wings with Chunky Blue Cheese',
      'Hot Cider Oatmeal',
      'Iced Chai Latte',
      'In the Garden of Cake',
      'Irish Bangers & Champ',
      'Irish Tacos',
      'Jackfruit Carnitas',
      'Jalapeno Corn Kickers',
      "Jason's Cheesy Mashed Potatoes",
      "Jennie's Blackstrap Molasses Cookies",
      "Joe's Bloody Mary",
      "Joe's Diner Macaroni Bolognese",
      "Joe-Joe's Cupcakes",
      'Kale & Bacon Breakfast Bagel',
      'Kale & Crispy Pork Belly',
      "Kick S'moreover Dip",
      "Kickin' Corn Dip",
      'Kiss My Cornbread with Jalapenos & Bacon',
      'Lasagna Carbonara',
      'Layered Salmon Quiche',
      'Leek & Bacon Egg Tottins',
      'Lemon Chicken Orzo Soup',
      'Lemon Ricotta Ravioli Salad',
      'Lemon-Mustard Vinaigrette',
      'Lemony Gin Refresher',
      'Lemony Grilled Chicken Thighs',
      'Lemony Shandy',
      'Linguine Limone Alfredo with Shrimp',
      'Loaded Baked Potato Soup Bread Bowl',
      'Loaded Potato Pancakes',
      'Loaded Totchos',
      "Mac N' Cheese & Pulled Pork Nachos",
      'Manchego Fig Bites',
      'Mango Black Bean Quinoa',
      'Mango Coconut Chia Frozen Pops',
      'Mango Limeadita',
      'Mango Melba Shortcake',
      'Mango Yogurt & Granola Parfait',
      'Mango, Mango Frozen Cheesecake',
      'Mangorita!',
      'Maple & Brown Sugar Butternut Squash',
      'Maple Spiced Whipped Cream',
      'Marshmallow Blondies',
      'Matcha Matcha Cupcakes',
      'Meatless Meatball BBQ Subs',
      'Mediterranean Seven-Layer Dip',
      'Mezza Luna Lasagna',
      "Miller's Irish Soda Bread",
      'Mini Caprese',
      'Mini Masala Meatballs',
      'Mini Sweet Potato Biscuits',
      'Mini Tropical Ice Cream Sandwiches',
      'Minted Peas & Goat Cheese',
      'Miso Shrimp & Veggie Stir-Fry',
      'MoJoe Toast',
      'Mozzarella & Roasted Corn Egg Bake',
      'Mushroom Miso Soup',
      'Neapolitan Joe-Joe Truffles',
      'No-Bake Cheesecake',
      'No-Bake Peanut Butter Chocolate Crisp Rice Cereal Treats',
      'Nutty Monkey Banana Bites',
      'Oat Beverage Matcha Latte',
      'Oatmeal Cookie Oatmeal',
      'Oatmeal Date Breakfast Shake',
      'Oktoberfest Feast',
      'Omega Bagel',
      'Orange Lime Mojito Mocktail',
      "Overnight Y'oats",
      'PB&J Protein Bowl',
      'PB&J Snack Mix',
      'PBLT with Smoked Aioli',
      'Palak Paneer Pasties',
      'Panettone & Egg Nog Bread Pudding',
      'Pantry Pasta',
      "Paul's Quinoa Chili",
      'Peach Coleslaw',
      'Peach Slab Pie',
      'Peachy-Peach Bellini',
      'Peanut Butter & Jelly Cinnamon Rolls',
      'Peanut Butter Cup Brownies',
      'Peanut Butter Cup Cinnamallow Treats',
      'Peeled Banana & Cookie Butter Cake',
      "Peppermint S'mores Cake",
      'Pepperoni Slab Pizza',
      'Pesto Kale Gnocchi',
      'Pesto Portabella Burger',
      'Pickled Party Mix',
      'Pineapple Quinoa',
      'Pineapple Upside Down Cake',
      'Pizza Bagels',
      'Pop Goes the Elote!',
      'Poppin Pumpkin Seeds',
      'Pork Belly Tacos',
      'Pork Loin with Honey Mustard',
      'Portobello Mushroom Stack',
      'Potato Pancakes with Asparagus & Poached Eggs',
      "Potsticker Soup's On!",
      'Preposterously Peanut Butter Cup Cookies',
      'Pressure Cooker Corned Beef & Cabbage',
      'Pretzel Bites & Beer Cheese Dip',
      'Prosciutto Melon Bites',
      'Protein Box',
      'Protein Power Bowl',
      'Pulled Jackfruit Sandwich',
      'Pulled Pork Sandwiches',
      'Pulled Pork Tacos',
      'Pumpkin Bars',
      'Pumpkin Choc-Oat Chip Muffins with Pumpkin Butter-Butter',
      'Pumpkin Madeleine Cookie Sandwiches',
      'Pumpkin Pie',
      'Pumpkin Pie Donuts with Maple Glaze',
      'Pumpkin Pie Milkshake',
      'Pumpkin Pie Spiced Mule',
      'Pumpkin Spice Honey Dip',
      'Pumpkin Spice Whipped Cream',
      "Queso Sonrisas, Ole'! Ole'! (Cheese Smiles, Hooray! Hooray!)",
      'Quick Colcannon',
      'Quinoa Con Pollo',
      'Quinoa Veggie Burgers with Avocado Tzatziki',
      'Raspberry Ricotta Toast',
      'Red Curry Chicken Drumsticks',
      'Refreshing Raspberry Lemonade',
      "Ridge Crispy S'moreover Bars",
      'Roasted Broccoli Salad',
      'Roasted Brussels Sprouts',
      'Roasted Carrots Of Many Colors',
      'Roasted Cauliflower Mezzelune & Fried Basil',
      'Roasted Corn & Feta Salad',
      'Roasted Lemon-Garlic Artichokes',
      'Roasted Shishito Pepper Sauce',
      'Roasted Squash Salad',
      'Roasted Strawberry Salad',
      'Roasted Veggie Bowl',
      'Rumble Cakes',
      'Rustic Mediterranean Pizza',
      'Rustic Peach Galette',
      'Salad Stuffed Sweet Potatoes',
      'Salmon Burgers',
      'Salted Caramel Speculoos Milkshake',
      'Sams Sweet Potato Soup',
      'Sassy Slaw Fish Tacos',
      'Sassy Stuffed Sliders',
      'Sausage & Kale Stuffing',
      'Sausage & Veggies',
      'Savory Butternut Squash Soup',
      'Scallops with Apples',
      'Scone Pinwheels with Honey Goat Cheese',
      'Seared Spicy Peanut Ahi Tuna Tacos',
      'Seriously Stuffed Twice-Baked Potatoes',
      'Sesame Quinoa Salad',
      'Shakshuka',
      'Shawarma Chicken & Rice Soup',
      'Shawarma Pizza',
      'Sheet Pan Fajitas',
      'Shepherds Pie',
      'Shrimp & Grits On A Stick',
      'Shrimp Bruschetta',
      'Shrimp Burger Salad',
      'Simple Strip Steak & Sauteed Veggies',
      'Sloppy Joe Sliders',
      'Slow Cooker Chicken Chile Verde',
      'Smashed Potatoes',
      'Smoked Aioli',
      'Smoked Paprika Potatoes',
      'Smoked Salmon & Cream Cheese Bagel',
      'Smokey Chimichurri Sauce',
      'Smoky Sriracha Baked Beans',
      'Soy Chorizo & Grilled Avocado Tacos',
      'Soy Chorizo Frittata',
      'Spaghetti Squash with Meatball Marinara',
      'Spiced Chai Pancakes',
      'Spiced Cider Pancakes',
      'Spiced Harvest Tea',
      'Spicy Avocado Hummus Toast',
      'Spicy Chicken & Waffle Bites',
      'Spicy Chicken Sandwich',
      'Spicy Fried Pickles',
      'Spicy Sausage and Kale Soup',
      'Spiked Watermelon Sparkler',
      'Spinach & Artichoke Sweet Potato Gratin',
      'Spinach Pie',
      'Spring Lentil Salad',
      'Sriracha BBQ Chicken Skewers',
      'Sriracha BBQ Meatballs',
      'Sriracha Furikake Tofu Fries',
      'Stay Home Soup',
      'Sticky Monkey Buns',
      'Strawberry Champagne Cake',
      'Strawberry Dome Cake',
      'Strawberry Icebox Cake',
      'Strawberry Lemon Muffins',
      'Strawberry Mule',
      'Street Corn Pasta Salad',
      'Stuffed Avocado',
      'Stuffed Soft Pretzels',
      'Stuffed Vine Tomatoes with Cheesy Hats',
      'Stuffing Muffins',
      'Sugar Pumpkin Pie Nuts',
      'Sunflower Seed Spread Cookies',
      'Sweet & Smoky Seared Tilapia',
      'Sweet & Spicy Glazed Carrots',
      'Sweet & Spicy Pecan-Crusted Salmon',
      'Sweet Balls of Fire',
      'Sweet Kale Slaw Turkey Burger',
      'Sweet Potato Chili Cheese Fries',
      'Sweet and Spicy Chicken Skewers',
      'Sweetheart Smoothie',
      'Tahini Caramel Brownies',
      'Tahini Salad Dressing',
      'Tahini, Pepita & Apricot Slawcos',
      'Tangy Grilled Chicken',
      'Taquito-lada Casserole',
      'Tastes Like Chicken Vegan Cauliflower Steaks',
      'Teeny Tiny Potatoes with Sweet Roasted Garlic',
      'Tempeh Crispy Noodle Salad',
      'Teriyaki BBQ Tofu with Soycutash Greens',
      'Teriyaki Chicken Fried Rice Stuffed Pineapple',
      'Thai-Style Peanut Pumpkin Soup',
      'Tikka Masala Burritos',
      'Tortellini Salad',
      'Toscano Cheese Board',
      'Trailblazer Bites',
      'Tropical Banana Bread',
      'Tropical Shrimp Salad',
      'Tuna Salad Pita',
      'Turkey Salad Sandwich',
      'Umami Dressing',
      'Umami Turkey Burgers',
      'Unexpected Cheddar Cheese Ball',
      'Vanilla Chai Cake with Spiced Apples',
      'Vegetable Stir Fry',
      'Vegetable and Soba Noodle Shrimp Stir Fry',
      'Veggie Burger with Almond Butter Turmeric Slaw',
      'W.O.W. Enchilada Casserole',
      'Waffle Sandwich',
      'Warm Cruciferous Cranberry Slaw',
      'What to do? Tofu!',
      'Willies Sweet Potato Pie',
      'Yogurt Crunch Waffle'
    ];
    final fuse = Fuzzy(
      titles,
      options: FuzzyOptions(
        findAllMatches: true,
        isCaseSensitive: false,
        tokenize: true,
        threshold: 0.3,
      ),
    );

    final result = fuse.search(recipe);
    List<int> searchResults = List<int>();
    result.forEach((element) {
      if (recipeTitles.containsKey(element.item)) {
        searchResults.add(int.parse(recipeTitles.get(element.item)));
      }
    });
    return searchResults;
  }

  /*
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CART
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

  static List<LinkedHashMap> getShoppingList() {
    // List<int> allShoppingItems = List<int>();
    List<LinkedHashMap> cart = List<LinkedHashMap>();
    shoppingList.toMap().forEach((recipeID, data) async {
      print("$recipeID : $data");
      cart.add(data);
    });
    return cart;
  }

  static Future<List<ShoppingIngredient>> getShoppingListByRecipe(int id) {}

  static void addRecipeToShoppingList(int recipeID) async {
    Recipe rec = await getRecipeWithID(recipeID);
    List<String> ing = rec.ingredients;
    Map<String, dynamic> data = {};
    for (int i = 0; i < ing.length; i++) {
      data['$i'] = {'title': ing[i], 'purchased': false, 'recipe_id': recipeID};
    }
    // print("Inserting $recipeID with value: $data");
    shoppingList.put(recipeID, data);
  }

  static removeRecipeFromShoppingList(int recipeID) async {
    // print("Trying to remove shopping list recipe id $recipeID");
    if (shoppingList.containsKey(recipeID)) {
      await shoppingList.delete(recipeID);
      // print("Succesfully deleted $recipeID from cart.");
    }
  }

  static clearAllFromShoppingList() async {
    // clear all shoppingList
    await shoppingList.clear();
  }

  static void setPurchased(int recipeID, String ingredient, bool wasPurchased) async {
    // In the shoppingList find the recipeID
    // Find the ingredient and change it to wasPurchased value.
    // print("Updating purchased value.");
    // print("Setting purchased value to $wasPurchased");
    if (shoppingList.containsKey(recipeID)) {
      LinkedHashMap shoppingListItem = await shoppingList.get(recipeID);
      print("shoppingListItem: $shoppingListItem");
      shoppingListItem.forEach((key, value) {
        if (value['title'] == ingredient) {
          value['purchased'] = wasPurchased;
        }
      });
    }
  }
}
